language: node_js
node_js:
  - '11.4.0'
install:
  - yarn
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
sudo: required
addons:
  chrome: stable
  firefox: latest
after_success: yarn codecov
